
name: Cypress Intergration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: '2'

    - name: Git Fetch
      run: git fetch origin main

    - name: Install dependencies
      run: |
        npm install --global yarn
        yarn install

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        headless: true
        record: false
        wait-on: 'http://localhost:8003'
        start: yarn run start:linux
        wait-on-timeout: 120
