
name: Cypress Intergration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
                         
    - name: Install dependencies
      run: |
        npm install

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        record: false
        wait-on: 'http://localhost:8003'
        start: cross-env PORT=8003 umi dev
        wait-on-timeout: 120
