# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.16.0 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --global yarn
          yarn install

      - name: Check installed versions
        run: |
          node -v
          npm -v
          yarn -v

      - name: Run unit tests
        run: |
          yarn run unit:test

      - name: "Tests Report"
        uses: dorny/test-reporter@v1
        with:
          name: Tests Report
          path: '__report__/junit/jest-component.xml'
          reporter: jest-junit
